@echo off

set WEBVIEW_DIR="%USERPROFILE%\.nuget\packages\microsoft.toolkit.forms.ui.controls.webview\5.0.0-preview.gb86cb1c4cb\lib\net462"

mkdir Release

csc -noconfig -nowarn:1701,1702 -nostdlib+ -errorreport:prompt -warn:4 -define:TRACE -highentropyva+ -reference:"%WEBVIEW_DIR%\Microsoft.Toolkit.Forms.UI.Controls.WebView.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\mscorlib.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Core.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Data.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Collections.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Drawing.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Windows.Forms.dll" -reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Xml.dll" -debug:pdbonly -filealign:512 -optimize+ -out:"Release\WebApp.dll" -ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" -subsystemversion:6.00 -target:library -utf8output -deterministic+ platform_windows.cs "%USERPROFILE%\AppData\Local\Temp\.NETFramework,Version=v4.6.2.AssemblyAttributes.cs"
copy "%WEBVIEW_DIR%\Microsoft.Toolkit.Forms.UI.Controls.WebView.dll" "Release\Microsoft.Toolkit.Forms.UI.Controls.WebView.dll"
copy "%WEBVIEW_DIR%\Microsoft.Toolkit.Forms.UI.Controls.WebView.pdb" "Release\Microsoft.Toolkit.Forms.UI.Controls.WebView.pdb"
copy "%WEBVIEW_DIR%\Microsoft.Toolkit.Forms.UI.Controls.WebView.xml" "Release\Microsoft.Toolkit.Forms.UI.Controls.WebView.xml"

CL -c -AI"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2" -AI"C:\Program Files (x86)\Windows Kits\10\References" -AI"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades" -Zi -clr -nologo -W3 -WX- -diagnostics:classic -O2 -D NDEBUG -D _WINDLL -D _UNICODE -D UNICODE -EHa -MD -GS -fp:precise -Zc:wchar_t -Zc:forScope -Zc:inline -Fo"Release\\" -Fd"Release\vc141.pdb" -TP -FU"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\mscorlib.dll" -FU"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.dll" -FU"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Windows.Forms.dll" -FU"Release\WebApp.dll" -FC -errorReport:queue -clr:nostdlib platform_windows.mcpp
CL -c -Zi -clr -nologo -W3 -WX- -diagnostics:classic -O2 -D NDEBUG -D _WINDLL -D _UNICODE -D UNICODE -EHa -MD -GS -fp:precise -Zc:wchar_t -Zc:forScope -Zc:inline -Fp"Release\Interop.pch" -Fa"Release\\" -Fo"Release\\" -Fd"Release\vc141.pdb" -FC -errorReport:queue "%USERPROFILE%\AppData\Local\Temp\.NETFramework,Version=v4.6.2.AssemblyAttributes.cpp"
link -ERRORREPORT:QUEUE -OUT:"Release\Interop.dll" -INCREMENTAL:NO -NOLOGO -MANIFEST -MANIFESTUAC:"level='asInvoker' uiAccess='false'" -manifest:embed -DEBUG:FULL -PDB:"Release\Interop.pdb" -TLBID:1 -DYNAMICBASE -FIXED:NO -NXCOMPAT -MACHINE:X64 -DLL "Release\platform_windows.obj"
